version: "3"
services:
  web:
    container_name: cmrr
    build:
      context: ../.
      dockerfile: ./docker/Dockerfile
    env_file:
      - .env
    volumes:
      - ../:/app/
    #network_mode: "host"
    ports:
      - "6000:6000"